//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
/*
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
*/
// 
// Codice sorgente generato automaticamente da wsdl, versione=4.6.1055.0.
// 


/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Web.Services.WebServiceBindingAttribute(Name="ServizioNumbersSoap", Namespace="http://numbers.jamaka.it/")]
public partial class ServizioNumbers : UnityEngine.Networking.UnityWebRequest  //System.Web.Services.Protocols.SoapHttpClientProtocol
{
    
  
    /// <remarks/>
    public ServizioNumbers() {
        this.url = "http://numbers.jemaka.it/NumberService.asmx";
    }
    
    /*
    public Solutions[] getSolutionsbyGrid(int idGrid) {
        object[] results = this.Invoke("getSolutionsbyGrid", new object[] {
                    idGrid});
        
        return ((Solutions[])(results[0]));
    }
    */

    public string getGrid() {
        string val = @"POST /NumberService.asmx HTTP/1.1
    Host: numbers.jemaka.it
    Content - Type: text / xml; charset = utf - 8
    Content - Length: length
    SOAPAction: \""http://numbers.jamaka.it/getGrid\""
     <? xml version = \""1.0\"" encoding = \""utf-8\"" ?>
     < soap : Envelope xmlns: xsi = \""http://www.w3.org/2001/XMLSchema-instance\"" xmlns: xsd = \""http://www.w3.org/2001/XMLSchema\"" xmlns: soap = \""http://schemas.xmlsoap.org/soap/envelope/\"" >
               
                 < soap:Body >
                
                    < getGrid xmlns = \""http://numbers.jamaka.it/\"" />
                 
                   </ soap:Body >
                  </ soap:Envelope > ";
        this.SetRequestHeader("1", val);
       return this.GetResponseHeader("1");
    }

    

   /*
    public Users getUser(string uuid) {
        object[] results = this.Invoke("getUser", new object[] {
                    uuid});
        return ((Users)(results[0]));
    }
    
    public string setUsers(Users u) {
        object[] results = this.Invoke("setUsers", new object[] {
                    u});
        return ((string)(results[0]));
    }
    
    public void updUserScore1(int id_user, float score1) {
        this.Invoke("updUserScore1", new object[] {
                    id_user,
                    score1});
    }
    
  */
}

public partial class Solutions {
    
    /// <remarks/>
    public int Id_solution;
    
    /// <remarks/>
    public int Id_grid;
    
    /// <remarks/>
    public float Number;
    
    /// <remarks/>
    public string Sequence;
    
    /// <remarks/>
    public float Difficulty;
    
    /// <remarks/>
    public string Note;
}

public partial class Users {
    
    /// <remarks/>
    public int Id_user;
    
    /// <remarks/>
    public string Nickname;
    
    /// <remarks/>
    public string Imei;
    
    /// <remarks/>
    public string Uuid;
    
    /// <remarks/>
    public System.DateTime Data_setup;
    
    /// <remarks/>
    public string Email;
    
    /// <remarks/>
    public string Service_id;
    
    /// <remarks/>
    public string Note;
    
    /// <remarks/>
    public float Score1;
    
    /// <remarks/>
    public float Score2;
    
    /// <remarks/>
    public float Bonus1;
    
    /// <remarks/>
    public float Bonus2;
}

public partial class Grids {
    
    /// <remarks/>
    public int Id_grid;
    
    /// <remarks/>
    public string Item;
    
    /// <remarks/>
    public System.DateTime Data_creation;
    
    /// <remarks/>
    public float Difficulty;
    
    /// <remarks/>
    public Solutions Solutions;
}

