//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumberService.ServizioNumbersSoap")]
    public interface ServizioNumbersSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSolutionsbyGrid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NumberService.Solutions[] getSolutionsbyGrid(int idGrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSolutionsbyGrid", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberService.Solutions[]> getSolutionsbyGridAsync(int idGrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGrid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NumberService.Grids getGrid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGrid", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberService.Grids> getGridAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Solutions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_solutionField;
        
        private int id_gridField;
        
        private float numberField;
        
        private string sequenceField;
        
        private float difficultyField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_solution {
            get {
                return this.id_solutionField;
            }
            set {
                this.id_solutionField = value;
                this.RaisePropertyChanged("Id_solution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Id_grid {
            get {
                return this.id_gridField;
            }
            set {
                this.id_gridField = value;
                this.RaisePropertyChanged("Id_grid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float Difficulty {
            get {
                return this.difficultyField;
            }
            set {
                this.difficultyField = value;
                this.RaisePropertyChanged("Difficulty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Grids : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_gridField;
        
        private string itemField;
        
        private System.DateTime data_creationField;
        
        private float difficultyField;
        
        private Solutions solutionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_grid {
            get {
                return this.id_gridField;
            }
            set {
                this.id_gridField = value;
                this.RaisePropertyChanged("Id_grid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Data_creation {
            get {
                return this.data_creationField;
            }
            set {
                this.data_creationField = value;
                this.RaisePropertyChanged("Data_creation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float Difficulty {
            get {
                return this.difficultyField;
            }
            set {
                this.difficultyField = value;
                this.RaisePropertyChanged("Difficulty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Solutions Solutions {
            get {
                return this.solutionsField;
            }
            set {
                this.solutionsField = value;
                this.RaisePropertyChanged("Solutions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServizioNumbersSoapChannel : NumberService.ServizioNumbersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServizioNumbersSoapClient : System.ServiceModel.ClientBase<NumberService.ServizioNumbersSoap>, NumberService.ServizioNumbersSoap {
        
        public ServizioNumbersSoapClient() {
        }
        
        public ServizioNumbersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServizioNumbersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServizioNumbersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServizioNumbersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NumberService.Solutions[] getSolutionsbyGrid(int idGrid) {
            return base.Channel.getSolutionsbyGrid(idGrid);
        }
        
        public System.Threading.Tasks.Task<NumberService.Solutions[]> getSolutionsbyGridAsync(int idGrid) {
            return base.Channel.getSolutionsbyGridAsync(idGrid);
        }
        
        public NumberService.Grids getGrid() {
            return base.Channel.getGrid();
        }
        
        public System.Threading.Tasks.Task<NumberService.Grids> getGridAsync() {
            return base.Channel.getGridAsync();
        }
    }
}
